# Generated by Django 2.2.5 on 2019-09-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, verbose_name='miasto')),
                ('kod', models.CharField(help_text='Wpisz kod pocztowy', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uczelnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, verbose_name='uczelnia')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=30)),
                ('imie', models.CharField(max_length=30)),
                ('dochod', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('roks', models.CharField(blank=True, default=0, max_length=3)),
                ('miasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studenci.Miasto')),
                ('uczelnia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studenci.Uczelnia')),
            ],
        ),
    ]
