# Generated by Django 2.2.5 on 2019-10-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miasto',
            options={'verbose_name_plural': 'miasta'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'studenci'},
        ),
        migrations.AlterModelOptions(
            name='uczelnia',
            options={'verbose_name_plural': 'uczelnie'},
        ),
    ]
